#!/usr/bin/env bash

for input in tests/render/fixtures/*/input.json; do
    for orient in horizontal vertical; do
        echo "draw $input $orient"
        python -m superrec2.cli draw \
            --orientation "$orient" < "$input" \
            > "${input%input.json}output-$orient.tex"
    done
done

git diff tests/render/fixtures
